"""initial schema

Revision ID: f264ab6fa6a3
Revises: 
Create Date: 2026-09-15 08:29:15.003132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f264ab6fa6a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cicd_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service')
    )
    op.create_table('conf_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('conf_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('credential_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('auth_type', sa.String(), nullable=False),
    sa.Column('key_file', sa.String(), nullable=True),
    sa.Column('key_fingerprint', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('pipeline_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('has_cicd', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('sha', sa.String(), nullable=True),
    sa.Column('web_url', sa.String(), nullable=True),
    sa.Column('collected_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service')
    )
    op.create_table('repo_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('collected_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo', 'tool', name='uq_repo_version')
    )
    op.create_table('runners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_token_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('server_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('version_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('ssh_user', sa.String(), nullable=False),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('access_method', sa.String(), nullable=False),
    sa.Column('gateway_id', sa.Integer(), nullable=True),
    sa.Column('credential_alias', sa.String(), nullable=True),
    sa.Column('access_control', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('needs_2fa', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_checked_at', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gateway_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['server_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conf_apply_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('from_sha', sa.String(), nullable=True),
    sa.Column('to_sha', sa.String(), nullable=True),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('backup_path', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('approved_at', sa.String(), nullable=True),
    sa.Column('applied_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conf_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('collected_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'path', name='uq_conf_snapshot')
    )
    op.create_table('connection_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('collected_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'tool', name='uq_tool_snapshot')
    )
    op.create_table('update_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('packages', sa.Text(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('collected_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', name='uq_update_snapshot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_snapshots')
    op.drop_table('tool_snapshots')
    op.drop_table('connection_tests')
    op.drop_table('conf_snapshots')
    op.drop_table('conf_apply_intents')
    op.drop_table('servers')
    op.drop_table('version_targets')
    op.drop_table('server_groups')
    op.drop_table('runners')
    op.drop_table('repo_versions')
    op.drop_table('pipeline_status')
    op.drop_table('credential_refs')
    op.drop_table('conf_targets')
    op.drop_table('conf_baselines')
    op.drop_table('cicd_targets')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
